#!/bin/bash

# helper script
# Used to wrap custom operations inside one script
############################# RH helper functions ##############################

_rh_try_ret_help()
{
	if [ ! -z $RH_RUNTIME_REQUEST_HELP ]
	then
		echo $1
		exit 1;
	fi
}

############################ RH built-in functions #############################

help()
{
	_rh_try_ret_help "Returns RH help with the list of all annotated functions"

	echo "RH stands for 'right hand'. It is a wrapper script wherein you can collect tiny commands."
	echo "Specify one righthand function from the followings:"

	RH_RUNTIME_REQUEST_HELP=true

	for f in ${RH_FUNCTIONS[@]}
	do
		# if the command has help
		if type $f | grep -qzP '{\s+_rh_try_ret_help '
		then
			echo -e "\t$f - "$($f)
		fi
	done
}

############################## Application area ################################

# Collection available commands
RH_FUNCTIONS=()

for func in `typeset -F | grep -Po '(?<=-f).*$' | sort`
do
	RH_FUNCTIONS+=($func);
done

# print help if nothing specified

if [ $# '<' '1' ]
then
	help
	exit 1
fi

# run command
for f in ${RH_FUNCTIONS[@]}
do
	if [ "$1" "=" "$f" ]
	then
		$f "${@:2}"
		exit $?
	fi
done

echo "Righthand function $1 not found, so now printing help..."
help
exit 1
